### ISSUE TITLE
Preference for pc/mac control/cmd keys

### ISSUE THREAD

**Issue by okyeron** [itsyourbedtime/orca#1]
Throwing this out there...

Seems like it would be cool to add a param for pc vs mac keyboard layout and allow people to set the behavior of the pc control and mac cmd keys (for copy/paste).

The mac CMD key codes are “KEY_LEFTMETA” and “KEY_RIGHTMETA” so it could be as easy as setting a flag in a param and then checking it around line [496](https://github.com/itsyourbedtime/orca/blob/28ae108edeaf8c46e3a9814f5aab5c693d355e04/orca.lua#L496) and using META instead?

I can try to work on this in the next day or two if I have time - or next week for sure.

**Comment by okyeron** [comment]
https://github.com/itsyourbedtime/orca/pull/2

**Comment by itsyourbedtime** [comment]
Linked them for now
