### ISSUE TITLE
Menu 'freezes'/skips certain parameters

### ISSUE THREAD

**Issue by joakimhellgren** [itsyourbedtime/orca#5]
The freeze only occur sometimes randomly after I change parameters of a sample (i.e Change filter envelope curves) / or when I load a new sample.

What happens is that when I scroll the menu, the screen freezes for a very brief moment and skips a selection of parameters. 
Example: I scroll from LFO2 of the first sample slot to the second, but the screen jump directly to the 'Bars' parameter of the next sample slot and I can't scroll back and alter these parameters because the same thing happens when I try to scroll back (jumps up to LFO2 again). 

The only way I can get it back to normal is by changing script.

(Had this issue with previous versions too, sorry for not reporting earlier)

Hope that makes sense! 
Thank you for your amazing work.

**Comment by joakimhellgren** [comment]
I just noticed that the parameters are actually still functioning when controlled with the knobs and updates values, it's just that it's not visible. 
It happened once now after changing a sample slots quality from high to low. The selection on the screen froze and I thought I would have to reset Norns, but it turns out that reverting back from low to high again fixes the screen freeze* !

*It seemed to have mysteriously solved the issue as well, as I can now select low quality without any screen freeze

**Comment by itsyourbedtime** [comment]
Coool
