### ISSUE TITLE
Saved project loads incorrect samples

### ISSUE THREAD

**Issue by oliviercreurer** [itsyourbedtime/orca#6]
Samples loaded during a session don't appear to be getting properly stored when that session is saved as a project -- instead, when the project is subsequently loaded, the params list seems to be pulling in arbitrary samples from my `tape` folder, in sequential order (i.e. sample 1 is `0016.wav`, sample 2 is `0017.wav`, etc.). I tried loading both the `.orca` and `.pset` files from the saved project list, to no avail, and was able to replicate the issue after saving a couple of new projects utilizing different samples -- the same `tape` samples seem to be getting pulled in each time. 

I'm currently running __v0.9.9.9__

**Comment by itsyourbedtime** [comment]
Fixed in ea06ddf
